spring:
  # Project name
  application:
    name: user-center
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.55.62.195:3306/user-center
    username: root
    password: Dw990831
  # session 失效时间(分钟)
  session:
    timeout: 86640
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: 120.55.62.195
    database: 0
    password: Dw990831
  # 整合swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  config:
#    activate:
#      on-profile: dev

# 端口
server:
  port: 8081
  servlet:
    context-path: /api
#    session:
#      cookie:
#        domain: localhost
